# Variables:
# - AUTH_PORT (default: 8080): Port to expose for Keycloak

version: '3.8'

services:
  db:
    image: notes-api/auth-db
    build:
      context: auth-db
    deploy:
      restart_policy:
        condition: any
        window: 10s
    shm_size: 128mb
    volumes:
      - kc-data:/var/lib/postgresql/data:rw
      - type: volume
        source: notes-secrets
        target: /secrets
        read_only: true
        volume:
          subpath: auth
    hostname: kc-db

  auth:
    image: notes-api/auth
    build:
      context: auth
    deploy:
      resources:
        limits:
          memory: 1G
      restart_policy:
        condition: any
        window: 10s
    volumes:
      - type: volume
        source: notes-secrets
        target: /secrets
        read_only: true
        volume:
          subpath: auth
    depends_on:
      - db
    command: start --optimized
    ports:
      - ${AUTH_PORT:-8080}:80
    environment:
      KC_DB_URL: "jdbc:postgresql://kc-db:5432/"
      KC_HTTP_ENABLED: true
      KC_HTTP_PORT: 80
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_STRICT: false

volumes:
  kc-data:
    external: true
  notes-secrets:
    external: true