# Variables:
# - AUTH_URL (required): Base URL for Keycloak
# - API_PORT (default: 3333): Port to expose for notes API

services:
  api:
    image: notes-api/api
    build:
      context: api
    volumes:
      - notes-data:/app/data:rw
    ports:
      - ${API_PORT:-3333}:80
    environment:
      NOTES_API_DB_DIR: /app/data
      NOTES_API_PORT: 80
      NOTES_API_AUTH_PROVIDER_URL: ${AUTH_URL:-https://localhost:9443}/realms/notes

volumes:
  notes-data:
    external: true