# Variables:
# - AUTH_URL (required): Base URL for Keycloak
# - API_PORT (required): Exposed port on which the API service will be hosted
# - PUBLIC_API_URL (required): Base URL that the API service will be hosted at (e.g. https://api.notes.quemot.dev)
# - WEB_PORT (required): Exposed port on which the web UI service will be hosted
# - PUBLIC_WEB_URL (required): Base URL that the web UI service will be hosted at (e.g. https://notes.quemot.dev)

services:
  api:
    image: notes-api/api
    volumes:
      - notes-data:/app/data:rw
    ports:
      - ${API_PORT:-3333}:80
    environment:
      NOTES_API_DB_DIR: /app/data
      NOTES_API_PORT: 80
      NOTES_API_AUTH_PROVIDER_URL: ${AUTH_URL:-https://localhost:9443}/realms/notes
      NOTES_API_REDIRECT_URL: ${PUBLIC_API_URL:-http://localhost:3333}/notes/auth/callback
      NOTES_API_ALLOWED_ORIGINS: "*"
      #NOTES_API_ALLOWED_ORIGINS: http://localhost:4444 # For local dev/testing of web UI
  web:
    image: notes-api/web
    ports:
      - ${WEB_PORT:-4444}:80
    environment:
      NOTES_WEB_PORT: 80
      NOTES_WEB_API_URL: ${PUBLIC_API_URL:-http://localhost:2222}/notes
      NOTES_WEB_AUTH_PROVIDER_URL: ${AUTH_URL:-https://localhost:9443}/realms/notes
      NOTES_WEB_REDIRECT_URL: ${PUBLIC_WEB_URL:-http://localhost:4444}/auth/callback
volumes:
  notes-data:
    external: true