# Variables:
# - AUTH_PORT (default: 8080): Port to expose for Keycloak

version: '2.4'

services:
  db:
    image: notes-api/auth-db
    build:
      context: auth-db
      labels:
        dev.quemot.notes.image.sha: $GIT_SHA
    restart: always
    shm_size: 128mb
    volumes:
      - kc-data:/var/lib/postgresql/data:rw
      - type: volume
        source: notes-secrets
        target: /secrets
        read_only: true
        volume:
          subpath: auth
    hostname: kc-db

  auth:
    image: notes-api/auth
    build:
      context: auth
      labels:
        dev.quemot.notes.image.sha: $GIT_SHA
    mem_limit: 0.5g
    memswap_limit: 0.5g
    restart: always
    volumes:
      - type: volume
        source: notes-secrets
        target: /secrets
        read_only: true
        volume:
          subpath: auth
    depends_on:
      - db
    command: start --optimized
    ports:
      - ${AUTH_PORT:-8080}:80
    environment:
      KC_DB_URL: "jdbc:postgresql://kc-db:5432/"
      KC_HTTP_ENABLED: true
      KC_HTTP_PORT: 80
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_STRICT: false

volumes:
  kc-data:
    external: true
  notes-secrets:
    external: true